<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\BankABS.Domain\BankABS.Domain.csproj" />
		<ProjectReference Include="..\BankABS.Data\BankABS.Data.csproj" />
	</ItemGroup>

</Project>